# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokemonTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReachabilitySwift'
  target 'PokemonTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokemonTestUITests' do
    # Pods for testing
  end

end